import asyncio
import json
import re
from pathlib import Path
from typing import Awaitable, Callable, TypedDict

import torch
from transformers import AutoTokenizer
from vllm import LLM, SamplingParams

from code_validation import CodeValidationError, validate_code

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

MODEL = "Qwen/Qwen2.5-Coder-14B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(MODEL)

llm = LLM(
    model=MODEL,
    dtype="bfloat16",
    gpu_memory_utilization=0.95,
)


sampling_params = SamplingParams(
    temperature=0.0,
    max_tokens=1024,
    repetition_penalty=1.05,
)


CONCURRENCY = 8
BATCH_SIZE = 4
YEARS = [2021, 2024]
DAYS = range(1, 25)
VARIANTS_PER_PROBLEM = 3

SYSTEM_PROMPT = (
    "You are a Python code generator.\n"
    "Output raw Python code only.\n"
    "Do not use markdown.\n"
    "Do not use triple backticks.\n"
    "Do not include explanations.\n"
    "Do not include example usage."
)

VARIANTS = [
    "Write a highly optimized solution focusing on performance.",
    "Use a functional programming style where possible.",
    "Avoid using advanced libraries; rely on basic Python constructs.",
    "Use concise code, minimizing line count.",
]

OUTPUT_PATH = Path("output.jsonl")


class Sample(TypedDict):
    """Base sample type for dataset code."""

    code: str
    label: str
    year: str
    day: str
    language: str


class LLMSample(Sample, total=True):
    """Sample type for code generated by LLMs."""

    model: str
    variant: str


class Job:
    year: int
    day: int
    variant_index: int

    def __init__(self, year: int, day: int, variant_index: int):
        self.year = year
        self.day = day
        self.variant_index = variant_index

    @property
    def id(self) -> str:
        return f"{self.year}-{self.day}-variant{self.variant_index}"


def strip_code_fences(text: str) -> str:
    text = text.strip()

    text = re.sub(r"^```python\s*", "", text)
    text = re.sub(r"^```\s*", "", text)
    text = re.sub(r"\s*```$", "", text)

    return text.strip()


def generate_code(prompts: list[str]) -> list[str]:
    formatted_prompts = []

    for prompt in prompts:
        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ]

        text = tokenizer.apply_chat_template(
            messages,
            add_generation_prompt=True,
            tokenize=False,
        )
        formatted_prompts.append(text)

    outputs = llm.generate(formatted_prompts, sampling_params)

    return [output.outputs[0].text.strip() for output in outputs]


def read_file(path: str):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return None


def build_prompt(problem: str, variant: str) -> str:
    return f"""
You are solving an Advent of Code problem using Python.
Return ONLY valid Python code. You MUST ensure the code is syntactically correct and adheres to the problem requirements.
You MUST NOT include any explanations, comments, or text outside of the code. The code should be self-contained and executable.

Additional constraint:
{variant}

Problem:
{problem}
""".strip()


def load_completed_jobs(path: Path) -> set[str]:
    if not path.exists():
        return set()

    completed_ids: set[str] = set()
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            try:
                sample = json.loads(line)
                job_id = build_completion_id(
                    int(sample["year"]),
                    int(sample["day"]),
                    VARIANTS.index(sample["variant"]),
                )
                completed_ids.add(job_id)
            except (json.JSONDecodeError, KeyError):
                continue

    return completed_ids


def build_jobs() -> list[Job]:
    jobs: list[Job] = []
    for year in YEARS:
        for day in DAYS:
            for variant_index in range(VARIANTS_PER_PROBLEM):
                jobs.append(Job(year, day, variant_index))
    return jobs


def build_completion_id(year: int, day: int, variant_index: int) -> str:
    return f"{year}-{day}-variant{variant_index}"


def create_sample(year: int, day: int, variant: str, code: str) -> LLMSample:
    return LLMSample(
        year=str(year),
        day=str(day),
        label="machine",
        variant=variant,
        code=code,
        language="python",
        model=MODEL,
    )


def create_jsonl_writer(path: Path) -> Callable[[LLMSample], Awaitable[None]]:
    lock = asyncio.Lock()

    f = open(path, "a", encoding="utf-8")

    async def write(sample: LLMSample):
        line = json.dumps(sample) + "\n"

        async with lock:
            f.write(line)
            f.flush()

    return write


async def process_batch(writer, jobs: list[Job]):
    prompts: list[str] = []
    metadata: list[tuple[Job, str]] = []

    for job in jobs:
        folder = f"generation/data/{job.year}/{job.day}"
        part1 = read_file(f"{folder}/part1.txt")
        part2 = read_file(f"{folder}/part2.txt")

        if not part1 or not part2:
            print(f"Missing problem statement for {job.year} day {job.day}, skipping.")
            continue

        problem = f"{part1}\n{part2}"
        variant = VARIANTS[job.variant_index]
        prompt = build_prompt(problem, variant)

        prompts.append(prompt)
        metadata.append((job, variant))

    generated_codes = generate_code(prompts)

    for (job, variant), code in zip(metadata, generated_codes):
        try:
            code = strip_code_fences(code)
            validate_code(code)

            sample = create_sample(job.year, job.day, variant, code)

            await writer(sample)

            print(f"Successfully processed {job.id}")

        except CodeValidationError as e:
            print(f"Validation failed for {job.id} {e}")


def chunked(lst: list[Job], size: int):
    for i in range(0, len(lst), size):
        yield lst[i : i + size]


async def main() -> None:

    completed_ids = load_completed_jobs(OUTPUT_PATH)
    all_jobs = build_jobs()
    pending_jobs = [job for job in all_jobs if job.id not in completed_ids]
    print(
        f"Total jobs: {len(all_jobs)}, Completed: {len(completed_ids)}, Pending: {len(pending_jobs)}"
    )

    if not pending_jobs:
        print("No pending jobs to process. Exiting.")
        return

    writer = create_jsonl_writer(OUTPUT_PATH)

    for batch in chunked(pending_jobs, BATCH_SIZE):
        await process_batch(writer, batch)


if __name__ == "__main__":
    asyncio.run(main())
