from dataclasses import dataclass
from typing import TypedDict


class Sample(TypedDict):
    """Base sample type for dataset code."""

    code: str
    label: str
    year: str
    day: str
    language: str


class LLMSample(Sample, total=True):
    """Sample type for code generated by LLMs."""

    model: str
    prompt: str
    code_variant: str
    style_variant: str


@dataclass(frozen=True)
class Job:
    year: int
    day: int
    prompt: str
    code_variant: str
    style_variant: str

    @property
    def id(self) -> str:
        return f"{self.year}-{self.day}-{self.code_variant}-{self.style_variant}"
